### PR TITLE
feat: support multiple targets

### PR DESCRIPTION
**Pull request by MickVanDuijn**
In an organization with multiple micro-services, each with multiple lambdas, the CloudWatch [**Rule** limit](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/cloudwatch_limits_cwe.html) of 100 is easily reached. With these additions, there can be a single warmer per micro-service, invoking all applicable lambdas with the desired concurrency.

### CODE REVIEW

**Comment by rictorres** [comment]
awesome!

**Comment by MickVanDuijn** [comment]
Note: most of the changes are due to `eslint`, so I could change it back if desired!

**Comment by rictorres** [comment]
@jeremydaly any chance you'd like to land this change?

**Comment by naorpeled** [comment]
I'm planning on reviewing this a bit later and then I'll work on a PR that adds type definitions to this, afterwards hopefully release this 🙏

**Review by naorpeled — COMMENTED** [review]
LGTM

**Pull request merged**
